### ISSUE TITLE
Prometheus alerts mapping

### ISSUE THREAD

**Issue by bzurkowski** [openrca/orca#34]
Prometheus provides a comprehensive set of [alerting rules](https://github.com/coreos/kube-prometheus/blob/master/manifests/prometheus-rules.yaml) for Kubernetes such as:

- `KubeContainerWaiting`
- `KubeDaemonSetNotScheduled`
- `KubeAPIErrorsHigh`

Open RCA enables connecting some of these alerts to elements present in the infra graph by using a [mapping file](https://github.com/openrca/orca/blob/master/helm/orca/config/alerts-mapping.yaml). The entries in the file are of the form:

```yaml
- name: KubePodCrashLooping
    source_mapping:
    origin: kubernetes
    kind: pod
    properties:
        name: pod
        namespace: namespace
```

The example above describes that whenever there is a `KubePodCrashLooping` alert detected, it should be mapped to graph element of `kubernetes` origin and `pod` kind, and connected to an element with properties `name` and `namespace` with values fetched from labels in alert payload, named correspondingly `pod` and `namespace`.

The mapping file is not complete. There is still a significant number of alerts that Open RCA cannot recognize. The remaining alerting rules should be reviewed and integrated into the mapping.
